# Generated by Django 4.2.7 on 2023-12-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuFeriaCL', '0005_userextension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextension',
            old_name='avatar',
            new_name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userextension',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
