# Generated by Django 4.2.6 on 2023-12-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuFeriaCL', '0008_alter_item_user_alter_post_user_alter_purchase_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity_available',
        ),
        migrations.AlterField(
            model_name='userextension',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
